version: 1.0.{build}

image: Visual Studio 2022

environment:
  nodejs_version: "20"
  ELECTRON_MIRROR: "https://npmmirror.com/mirrors/electron/"
  ELECTRON_BUILDER_BINARIES_MIRROR: "https://npmmirror.com/mirrors/electron-builder-binaries/"

install:
  - ps: |
      npm install -g npm@6
      $env:Path = "C:\Users\appveyor\AppData\Roaming\npm;$env:Path"

  - npm install --legacy-peer-deps --no-audit --no-fund

build_script:
  - npm run dist

artifacts:
  - path: release\*.exe
    name: RouterX-Admin-Windows

deploy:
  - provider: GitHub
    release: $(APPVEYOR_REPO_TAG_NAME)
    description: "RouterX Admin Windows Build"
    auth_token: "%GITHUB_TOKEN%"
    artifact: RouterX-Admin-Windows
    on:
      appveyor_repo_tag: true
